#!/usr/bin/env bash
set -euo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: 55576f7cf8659d49aa28b3fca8039b6e05d47231

test "$(sha256sum .github/workflows/container-deployment.yml | cut -d' ' -f1)" = "3681c04d54429217d8a4772b7a7135946dfa3c423309edad3fbe18e525bd8e27"
test "$(sha256sum scripts/container_deployment_controller.py | cut -d' ' -f1)" = "d9af3f6c355f2ce0bfde6a5736f0648a8d94cf03d4affbfb98cc0ba295df4252"
test "$(sha256sum scripts/container_deployment_preflight.py | cut -d' ' -f1)" = "93ed570b718f7dbc38fa06a846f53119cdffff3b8cf3f40ccf18ea153e7bfb8f"
test "$(sha256sum scripts/deployment-receipt.schema.json | cut -d' ' -f1)" = "079524c852e50e1a1675b11fd5d7d94aa4e3b0dc3e9cc0535c56c78c549689f4"
test "$(sha256sum .github/workflows/container-deployment-code-review.yml | cut -d' ' -f1)" = "3ccdac6f067d94ad2b0e7a161d1b2afec9d92c99c30df53987c1fe5e679c32c8"
test "$(sha256sum .github/workflows/container-deployment-security-review.yml | cut -d' ' -f1)" = "89729e3c273a8ca632bf50c0f4201878b5aa5ad9324f3adeca120f909798dcfb"
test "$(sha256sum .github/workflows/container-deployment-ai-review.yml | cut -d' ' -f1)" = "3d1fd4d42338935192c2b8ad2da729ec1a36cfd209e08e88d6f548000142efb7"
test "$(sha256sum .github/workflows/container-deployment-review-producer.yml | cut -d' ' -f1)" = "7edd405f8aefd2d33a5b584ade46e769ceb71c974f6de4a8af86d73b8a35f6ee"
test "$(sha256sum scripts/container_deployment_review_producer.py | cut -d' ' -f1)" = "a8b3371e03d163da2832c7f762ace461b644a7bb5d2e97df57bd7a1cb047b1b8"
test -f "container-deployment.json"
jq -e '
  .schemaVersion == 1 and
  (.reviewAuthority | keys | sort == ["ai", "code", "security"]) and
  ([.reviewAuthority[].installationId] | all(type == "number" and . > 0)) and
  (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) and
  (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) and
  .cliCommand == ["verjson-cloud"] and
  (.evidenceCommand | length == 2) and
  (.probeCommand | length == 2) and
  (.fleets | type == "object" and length > 0)
' "container-deployment.json" >/dev/null
while IFS= read -r adapter; do
  test -f "$adapter"
  test ! -L "$adapter"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "container-deployment.json")
grep -qF 'container-deployment.yml@55576f7cf8659d49aa28b3fca8039b6e05d47231' .github/workflows/container-deployment.yml
grep -qF 'contract-ref: 55576f7cf8659d49aa28b3fca8039b6e05d47231' .github/workflows/container-deployment.yml
! grep -Eq 'secrets:|environment:|RUNNER_DEPLOY_TOKEN|DIGITALOCEAN_RUNNER_FLEET_TOKEN|GH_RUNNER_REGISTRATION_APP_PRIVATE_KEY|:latest|:stable'   .github/workflows/container-deployment.yml
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "with"}
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@")
assert set(workflow["permissions"]) == {
    "actions", "attestations", "checks", "contents", "packages", "pull-requests"
}
PY
