#!/usr/bin/env bash
set -euo pipefail
ref='8e67aa60b66df8da17724ab458c58fae2cf58b51'
printf '%s  %s\n' '8e95ada9b1bd1a88903e352018999211dc98b8cae7de50221dc3360c981e88c8' .github/workflows/container-release.yml | sha256sum --check --strict
grep -Fq "container-release.yml@$ref" .github/workflows/container-release.yml
grep -Fq "contract-ref: $ref" .github/workflows/container-release.yml
grep -q "workflow_dispatch:" .github/workflows/container-release.yml
! grep -Eq '^  (push|pull_request):' .github/workflows/container-release.yml
grep -q 'RELEASE_APP_CLIENT_ID' .github/workflows/container-release.yml
grep -q 'release_environment: release-app' .github/workflows/container-release.yml
grep -q '^    secrets: inherit$' .github/workflows/container-release.yml
! grep -Eq 'PRIVATE_KEY' .github/workflows/container-release.yml
legacy_release_token='RELEASE_'"TOKEN"
legacy_org_release_token='VERJSON_RELEASE_'"TOKEN"
! grep -Eq "$legacy_release_token|$legacy_org_release_token" .github/workflows/container-release.yml
test -f scripts/container_release_promotion.py
test -f scripts/container_release_manifest.py
test -f scripts/container_artifact_extract.py
test -f scripts/container_attestation_verify.py
printf '%s  %s\n' 'f4a672502ffb13d83945f473f33de03d9b8fc98ac22a4681739c6856d0194e6a' scripts/container_release_promotion.py | sha256sum --check --strict
printf '%s  %s\n' '93989f1df517562529924d6b9542976865234fda5174ac11fa352331671810d7' scripts/container_release_manifest.py | sha256sum --check --strict
printf '%s  %s\n' 'f485dcbf63dc15c530399f07cca876f398ab6520e932a2c1eb34deda1fef6748' scripts/container_artifact_extract.py | sha256sum --check --strict
printf '%s  %s\n' 'b4e4bc5a08ad3e40e430de4d499419d8c91c186ced01d72ab032136eca9a989b' scripts/container_attestation_verify.py | sha256sum --check --strict
grep -q '^  attestations: write$' .github/workflows/container-release.yml
grep -q 'Generated by Verjson/.github/scripts/gen-container-release.sh' .github/workflows/container-release.yml
reconcile_allowlist='["images/rust.Dockerfile","images/node.Dockerfile","images/python.Dockerfile","images/go.Dockerfile","Dockerfile.pwsh","README.md"]'
grep -Fqx "      reconcile-allowlist: '$reconcile_allowlist'" .github/workflows/container-release.yml
test -f scripts/release-reconcile.sh
test ! -L scripts/release-reconcile.sh
test -x scripts/release-reconcile.sh
test -f 'images/rust.Dockerfile'
test ! -L 'images/rust.Dockerfile'
test -f 'images/node.Dockerfile'
test ! -L 'images/node.Dockerfile'
test -f 'images/python.Dockerfile'
test ! -L 'images/python.Dockerfile'
test -f 'images/go.Dockerfile'
test ! -L 'images/go.Dockerfile'
test -f 'Dockerfile.pwsh'
test ! -L 'Dockerfile.pwsh'
test -f 'README.md'
test ! -L 'README.md'
echo 'container release contract passed'
