#!/usr/bin/env bash
set -euo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: 3af4580b7d345602891fea91c2684b3bb7892c36

test "$(sha256sum .github/workflows/container-deployment.yml | cut -d' ' -f1)" = "76f33d6ac497c06e8765a5af10d5d48e9494db5ed3ba92543f6973a34ddd829a"
test "$(sha256sum scripts/container_deployment_controller.py | cut -d' ' -f1)" = "1c91abf65f8dda0451a351b72bd18ec0043a6d790a213ec543cf7e5387688546"
test "$(sha256sum scripts/container_deployment_transport.py | cut -d' ' -f1)" = "10f02cc7a240aaf397bbbc2a6b8523a193fe4e12633b8c0ef73d6d2ecf5d2bfd"
test "$(sha256sum scripts/container_deployment_preflight.py | cut -d' ' -f1)" = "820013d4d434dd22e5406a3ed79622e29d51ba5f01696fab05f7d60203f2f4c2"
test "$(sha256sum scripts/deployment-receipt.schema.json | cut -d' ' -f1)" = "079524c852e50e1a1675b11fd5d7d94aa4e3b0dc3e9cc0535c56c78c549689f4"
test "$(sha256sum .github/workflows/container-deployment-code-review.yml | cut -d' ' -f1)" = "c69a5717c94d871d7756ddc80d93c50d1e554b2da605a9f342b10be69fd19c6a"
test "$(sha256sum .github/workflows/container-deployment-security-review.yml | cut -d' ' -f1)" = "43d06981511a8f8fa2eb682480e9e38a3fc1eb0b720b37f9cfe2153644f65a01"
test "$(sha256sum .github/workflows/container-deployment-ai-review.yml | cut -d' ' -f1)" = "37018dc57c1d0d4805857514e6f8c9f62614454e0c780ccc2b6644fb6a8b7e52"
test "$(sha256sum .github/workflows/container-deployment-review-producer.yml | cut -d' ' -f1)" = "7edd405f8aefd2d33a5b584ade46e769ceb71c974f6de4a8af86d73b8a35f6ee"
test "$(sha256sum scripts/container_deployment_review_producer.py | cut -d' ' -f1)" = "78ea6a075f1a840912e4ce9752715e520eb96693518f7035e21d088d675034fc"
test -f "container-deployment.json"
jq -e '
  .schemaVersion == 1 and
  (.reviewAuthority | keys | sort == ["ai", "code", "security"]) and
  ([.reviewAuthority[].installationId] | all(type == "number" and . > 0)) and
  (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) and
  (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) and
  .cliCommand == ["verjson-cloud"] and
  (.evidenceCommand | length == 2) and
  (.probeCommand | length == 2) and
  (.fleets | type == "object" and length > 0)
' "container-deployment.json" >/dev/null
while IFS= read -r adapter; do
  test -f "$adapter"
  test ! -L "$adapter"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "container-deployment.json")
grep -qF 'container-deployment.yml@3af4580b7d345602891fea91c2684b3bb7892c36' .github/workflows/container-deployment.yml
grep -qF 'contract-ref: 3af4580b7d345602891fea91c2684b3bb7892c36' .github/workflows/container-deployment.yml
! grep -Eq 'secrets:|environment:|RUNNER_DEPLOY_TOKEN|DIGITALOCEAN_RUNNER_FLEET_TOKEN|GH_RUNNER_REGISTRATION_APP_PRIVATE_KEY|:latest|:stable'   .github/workflows/container-deployment.yml
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py scripts/container_deployment_transport.py
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "with"}
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@")
assert set(workflow["permissions"]) == {
    "actions", "attestations", "checks", "contents", "packages", "pull-requests"
}
PY
