#!/usr/bin/env bash
set -euo pipefail
# Generated by Verjson/.github/scripts/gen-container-deployment.sh; do not edit.
# Contract: 91c12ff5931ab7eb7c9a76276c2cadae5d780174

test "$(sha256sum .github/workflows/container-deployment.yml | cut -d' ' -f1)" = "72c93606919e54a541272d0de7975adc2dad367a70b514190ec538d34166d66a"
test "$(sha256sum scripts/container_deployment_controller.py | cut -d' ' -f1)" = "1aea8dd2389576aff80683dab3108bffcb19846f0c326573f34d0d8c908ef182"
test "$(sha256sum scripts/container_deployment_transport.py | cut -d' ' -f1)" = "aa9941964264ba8be766a926e97df9c9732a044268acbe0dadb0b42d8c8da082"
test "$(sha256sum scripts/container_deployment_preflight.py | cut -d' ' -f1)" = "6758d8b1a7d7fb3f76ed536cbca2a13086c8d3f94fa432158332255ae51d2c89"
test "$(sha256sum scripts/deployment-receipt.schema.json | cut -d' ' -f1)" = "079524c852e50e1a1675b11fd5d7d94aa4e3b0dc3e9cc0535c56c78c549689f4"
test "$(sha256sum .github/workflows/container-deployment-code-review.yml | cut -d' ' -f1)" = "25363a083dcaf1a2b6c43f1f48992db35cf922d609dcc3481c1658b67ea78754"
test "$(sha256sum .github/workflows/container-deployment-security-review.yml | cut -d' ' -f1)" = "ab3c31a02b025da46137b85a621641d262741c02c8068fe9f47223fb36a678b8"
test "$(sha256sum .github/workflows/container-deployment-ai-review.yml | cut -d' ' -f1)" = "fe0de6e4dbd0b629aa2de7f2655171045b892be8f76a973d630538ef37b98923"
test "$(sha256sum .github/workflows/container-deployment-review-producer.yml | cut -d' ' -f1)" = "7edd405f8aefd2d33a5b584ade46e769ceb71c974f6de4a8af86d73b8a35f6ee"
test "$(sha256sum scripts/container_deployment_review_producer.py | cut -d' ' -f1)" = "a1351fb7489f85a1e79514398a5211dc8bb5f94ae8d25cbc1fa7d0577c5c48b7"
test -f "container-deployment.json"
jq -e '
  .schemaVersion == 1 and
  (.reviewAuthority | keys | sort == ["ai", "code", "security"]) and
  ([.reviewAuthority[].installationId] | all(type == "number" and . > 0)) and
  (.reviewAuthority.ai.sourceAppId | type == "number" and . > 0) and
  (.reviewAuthority.ai.sourceCheckName | type == "string" and length > 0) and
  .cliCommand == ["verjson-cloud"] and
  (.evidenceCommand | length == 2) and
  (.probeCommand | length == 2) and
  (.fleets | type == "object" and length > 0)
' "container-deployment.json" >/dev/null
while IFS= read -r adapter; do
  test -f "$adapter"
  test ! -L "$adapter"
done < <(jq -r '.evidenceCommand[1], .probeCommand[1]' "container-deployment.json")
grep -qF 'container-deployment.yml@91c12ff5931ab7eb7c9a76276c2cadae5d780174' .github/workflows/container-deployment.yml
grep -qF 'contract-ref: 91c12ff5931ab7eb7c9a76276c2cadae5d780174' .github/workflows/container-deployment.yml
! grep -Eq 'secrets:|environment:|RUNNER_DEPLOY_TOKEN|DIGITALOCEAN_RUNNER_FLEET_TOKEN|GH_RUNNER_REGISTRATION_APP_PRIVATE_KEY|:latest|:stable'   .github/workflows/container-deployment.yml
python3 -m py_compile scripts/container_deployment_controller.py scripts/container_deployment_preflight.py scripts/container_deployment_transport.py
python3 -m json.tool scripts/deployment-receipt.schema.json >/dev/null
python3 - .github/workflows/container-deployment.yml <<'PY'
import sys
import yaml

with open(sys.argv[1], encoding="utf-8") as stream:
    workflow = yaml.safe_load(stream)
trigger = workflow.get("on", workflow.get(True))
assert set(trigger) == {"workflow_dispatch"}
job = workflow["jobs"]["deploy"]
assert set(job) == {"uses", "with"}
assert job["uses"].startswith("Verjson/.github/.github/workflows/container-deployment.yml@")
assert set(workflow["permissions"]) == {
    "actions", "attestations", "checks", "contents", "packages", "pull-requests"
}
PY
